### ISSUE TITLE
Handle `event` frontmatter

### ISSUE THREAD

**Issue by ear1grey** [pompeybug/website#27]
Historical articles have `event` front-matter thus:

```YAML
event:
    date:  2015-08-30 10:00
    end: 2015-08-30 14:00
    location: A nice pub, Somewhere, Portsmouth
    contact: Billy Biker
    email: billy@pompey.bike
```

It would be really useful to present this in a standardised format (via a template) and also to process the collection of events and make them available in iCal format.
