### ISSUE TITLE
Map Page and Frontmatter

### ISSUE THREAD

**Issue by ear1grey** [pompeybug/website#66]
If we included a `map` frontmatter e.g.

```
map:
  type: bike shop
  lat: 12445
  long: 64678
```

This might go into a generated map page that would show points of interest.

This might use/complement a markdown extension for maps.
